### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by jethrogb** [nrc/xmas-elf#22]
I'm getting ready to release one of my projects depending on xmas-elf, but I can't put it on crates.io because of the git dependency.

**Comment by nrc** [comment]
Available at https://crates.io/crates/xmas-elf

**Comment by jethrogb** [comment]
The crate is broken. It contains `main.rs` but not `lib.rs`.

**Comment by jethrogb** [comment]
Also it contains a binary

**Comment by nrc** [comment]
Whoops, sorry. Let's try to fix that...

**Comment by nrc** [comment]
Ok, hopefully that should have the lib rather than bin now (I made v0.2 for it).

**Comment by jethrogb** [comment]
Thanks, that works better :) You might want to yank 0.1.0
