### ISSUE TITLE
Don't use enums in Pod types

### ISSUE THREAD

**Issue by philipc** [nrc/xmas-elf#35]
We can't guarantee that the raw data is valid, so it's not safe to interpret it as an enum value. It should use a new type instead.

This is causing the `interpret_class` test to fail when giving a value of `42u8` for the class.

I notice that this is already done for `struct Type_`, with an `enum Type` for the constants. Should the rest of the enums be converted to this style?

**Comment by nrc** [comment]
Yeah, I suppose it would be better to handle all enums like that.
