### ISSUE TITLE
Program header flags are private and cannot be read

### ISSUE THREAD

**Issue by kevinaboos** [nrc/xmas-elf#43]
https://github.com/nrc/xmas-elf/blob/ae8acad7eff85bd291e2855bbb8c4d7d7d77214d/src/program.rs#L195

Flags are not useful because you cannot check the value of the flags element (`flags.0` doesn't work) to see which flags are set (W, R, X) because the `pub struct Flags(u32)` is not public. It should either be public, or there should be getter/contain methods such as `Flags::is_read()`/`is_write()`/`is_execute()`.

**Comment by aleksander** [comment]
I'm missing this feature too. Could you please create pull request for it? Or could I?

**Comment by nrc** [comment]
happy to take a PR!

**Comment by aleksander** [comment]
Not sure how this should be done so I did two pull requests.

**Comment by nrc** [comment]
I think both approaches might be useful for different users, so merged both PRs.

**Comment by kevinaboos** [comment]
Can you push the latest version to crates.io? Thanks!

**Comment by nrc** [comment]
I released v0.6.1 with this change
